### ISSUE TITLE
Add support for pager duty services

### ISSUE THREAD

**Issue by softprops** [aws-ia/cloudformation-pagerduty-resource-providers#42]
I would love to be able to manage pagerduty services using this tool. Are there any plans for this?

**Comment by CloudChoom** [comment]
Hi @softprops thanks for the input. We'll take a look at adding that resource type. Are there any other 3rd party resource types you'd like to see (both PagerDuty and non-PagerDuty)?

**Comment by softprops** [comment]
For completeness I there might need to be a way to configure pd  cw integration 

Here's a common usecase at my company when setting up a new service for completeness

in a service template...
* setup your service infra as a cf/sam template ecs/lambda/ect. 
* set up monitoring with cloudwatch metrics
* setup topic subscriptions for ok/error states

then separately...
* go set up pager duty service for the service to notify oncall engineers grab an cloudwatch integration url 

then come back and...
* update the topic subscriptions in infra template with the pager duties cw integration url


the end result looking something like

```yaml
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      # topic definition
      Subscription:
        - Protocol: https
          Endpoint: PAGER_DUTY_INTEGRATION_URL

  Alarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      # alarm definition
      OKActions:
        - !Ref SnsTopic
      AlarmActions:
        - !Ref SnsTopic
  ```

What'd I'd love to be able to do is to set up the all of this in one infra template and not have to go manage pager duty service to get that integration url separately.

```
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      # topic definition
      Subscription:
        - Protocol: https
          Endpoint: !GetAtt MyPDService.IntegrationURL // or something similar
 ```
